**ARRAY OPERATIONS**

In [1]:
import numpy as np

Arithmetic Operations

Vector

In [2]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 2, 3, 4, 5])
print(x)
print(y)

[1 2 3 4 5]
[1 2 3 4 5]


In [3]:
print(x + y)

[ 2  4  6  8 10]


In [4]:
print(x - y)

[0 0 0 0 0]


In [5]:
print(x * y)

[ 1  4  9 16 25]


In [6]:
print(x / y)

[1. 1. 1. 1. 1.]


In [7]:
print(x // y)

[1 1 1 1 1]


In [8]:
print(x ** y)

[   1    4   27  256 3125]


Matrix

In [9]:
x = np.arange(1,10).reshape((3,3))
y = np.arange(9,0,-1).reshape((3,3))

print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [10]:
print(x + y)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [11]:
print(x - y)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [12]:
print(x * y)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [13]:
print(x / y)

[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [14]:
print(x // y)

[[0 0 0]
 [0 1 1]
 [2 4 9]]


In [15]:

print(x ** y)

[[   1  256 2187]
 [4096 3125 1296]
 [ 343   64    9]]


**Broadcasting**

Vector

In [16]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [17]:
print(arr + 100)

[101 102 103 104 105]


In [18]:
print(arr * 2)

[ 2  4  6  8 10]


Matrix

In [19]:
arr = np.arange(1,10).reshape((3,3))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
print(arr + 100)

[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [21]:
print(arr * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


**Deep and Shallow copy**

Shallow copy

In [22]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [23]:
b = a 
print(b)

[1 2 3 4 5]


In [24]:
b[0] = 9

print(a)
print(b)

[9 2 3 4 5]
[9 2 3 4 5]


Deep copy

In [25]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [26]:
y = a.copy()
print(y)

[9 2 3 4 5]


In [27]:
y[0] = 9
print(x)
print(y)

[1 2 3 4 5]
[9 2 3 4 5]


In [28]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [29]:
arr[0:6] * 5
print(arr)

[1 2 3 4 5 6 7 8 9]


Matirx Operations

In [30]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [31]:
B = np.array([[5,6],[7,8]])
print(B)

[[5 6]
 [7 8]]


In [32]:
print(A @ B)

[[19 22]
 [43 50]]


In [33]:
print(A.dot(B))

[[19 22]
 [43 50]]


In [34]:
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [35]:
print(np.matmul(A,B))

[[19 22]
 [43 50]]


In [36]:
print(A.__matmul__(B))

[[19 22]
 [43 50]]


Transpose

In [37]:
arr = np.arange(1,10).reshape((3,3))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
print(arr.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [39]:
print(arr.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


**Advance Array Manipulation**

Stacking Array

In [40]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8,])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [41]:
print(np.vstack((a,b)))

[[1 2 3 4]
 [5 6 7 8]]


In [42]:
print(np.hstack((a,b)))

[1 2 3 4 5 6 7 8]


In [43]:
print(np.column_stack((a,b)))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


Splitting Array

In [44]:
arr = np.arange(1,17).reshape(4,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [45]:
np.hsplit(arr, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [46]:
a = np.hsplit(arr, 4)

In [47]:
a[0]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [48]:
for i in a:
    print(i)

[[ 1]
 [ 5]
 [ 9]
 [13]]
[[ 2]
 [ 6]
 [10]
 [14]]
[[ 3]
 [ 7]
 [11]
 [15]]
[[ 4]
 [ 8]
 [12]
 [16]]


In [49]:
np.vsplit(arr, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [50]:
a = np.vsplit(arr, 4)

In [51]:
for i in a:
    print(i)

[[1 2 3 4]]
[[5 6 7 8]]
[[ 9 10 11 12]]
[[13 14 15 16]]
