In [1]:
import numpy as np

**NUMPY INDEXING AND SLICING OF VECTORS**

In [2]:
arr = np.arange(11,21)
print(arr)

[11 12 13 14 15 16 17 18 19 20]


In [3]:
print(arr[1])
print(arr[5])

12
16


In [4]:
print(arr[:6])
print(arr[6:])

[11 12 13 14 15 16]
[17 18 19 20]


In [5]:
print(arr[1:6])

[12 13 14 15 16]


In [6]:
print(arr[0::1])
print(arr[0::2])
print(arr[0::3])

[11 12 13 14 15 16 17 18 19 20]
[11 13 15 17 19]
[11 14 17 20]


**NUMPY INDEXING AND SLICING OF MATRIX**

In [7]:
arr = np.arange(1,31).reshape((6,5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [8]:
print(arr[0,1])
print(arr[3,0])
print(arr[4,1])

2
16
22


In [9]:
print(arr[:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
print(arr[3:])

[[16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [11]:
print(arr[:,:3])

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]
 [21 22 23]
 [26 27 28]]


In [12]:
print(arr[:,3:])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]
 [29 30]]


In [13]:
print(arr[2:, 2:])

[[13 14 15]
 [18 19 20]
 [23 24 25]
 [28 29 30]]


In [14]:
print(arr[:4,:4])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]


**BOOLEAN INDEXING**

In [15]:
arr = np.arange(11,21)
print(arr)

[11 12 13 14 15 16 17 18 19 20]


In [16]:
even_arr = arr % 2 == 0
print(even_arr)

[False  True False  True False  True False  True False  True]


In [17]:
even_arr = arr[even_arr]
print(even_arr)

[12 14 16 18 20]
