NumPy Library

In [1]:
import numpy as np

Basic Array Creation

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array Generation Functions

In [4]:
arr = np.arange(5,10)
print(arr)

[5 6 7 8 9]


In [5]:
arr = np.arange(2,21,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [6]:
arr = np.zeros((6,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
arr = np.zeros((6,5), dtype=int)
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [8]:
arr = np.ones((6,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
arr = np.ones((6,5), dtype=int)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [10]:
arr = np.full((6,5), 7)
print(arr)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [11]:
arr = np.full((6,5), 9, dtype=float)
print(arr)

[[9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]]


In [12]:
arr = np.linspace(0,1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Random Generation Functions

In [13]:
arr = np.random.rand(5) # 0 - 1
print(arr)

[0.16231657 0.78333775 0.11180129 0.02822935 0.94971889]


In [14]:
arr = np.random.randn(5) # -3 - 3
print(arr)

[-1.46964243  1.28519158  0.81938938  1.30993762  0.64991039]


In [15]:
arr = np.random.randint(10, 20, 10)
print(arr)

[19 19 13 17 15 12 10 16 17 10]


Array Attributes

In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
print(arr.shape)

(3, 3)


In [18]:
print(arr.size)

9


In [19]:
print(arr.dtype)

int64


In [20]:
print(arr.ndim)

2


Array Methods

In [21]:
print(arr.min())
print(arr.max())

1
9


In [22]:
print(arr.argmin())
print(arr.argmax())

0
8


In [23]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

45
[12 15 18]
[ 6 15 24]


In [25]:
print(np.sum(arr))
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

45
[12 15 18]
[ 6 15 24]


In [26]:
print(arr.mean())
print(arr.std())

5.0
2.581988897471611


Reshaping and Resizing

In [27]:
arr = np.arange(1,31)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [28]:
arr = arr.reshape((6,5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [29]:
arr = arr.reshape((1,30))
print(arr)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30]]


In [30]:
arr = np.reshape(arr, (6,5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
