In [1]:
import numpy as np

**Valid Sudoku**

In [2]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [3]:
print(np.sum(s[0:3,0:3]))
print(np.sum(s[0:3,3:6]))
print(np.sum(s[0:3,6:9]))

print(np.sum(s[3:6,0:3]))
print(np.sum(s[3:6,3:6]))
print(np.sum(s[3:6,6:9]))

print(np.sum(s[6:9,0:3]))
print(np.sum(s[6:9,3:6]))
print(np.sum(s[6:9,6:9]))


45
45
45
45
45
45
45
45
45


In [4]:
for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        print(np.sum(s[i:i+3,j:j+3]))

45
45
45
45
45
45
45
45
45


In [5]:
row = np.sum(s, axis=1)
col = np.sum(s, axis=0)

row_check = row == 45
col_check = col == 45

if all(row_check) and all(col_check):
    print("valid row and column wise")
else:
    print("invalid")



valid row and column wise


**General Questions**

Columns: [age, math_marks, science_marks]

In [6]:
data = np.array([
    [18, 85, 78],
    [19, 92, 88],
    [17, 76, 95],
    [18, 65, 70],
    [20, 90, 85]
])

Get the shape of the matrix

In [7]:
print(data.shape)

(5, 3)


Find the average age of students

In [8]:
shape = data.shape
avg = np.sum(data[:,:1]) / shape[0]
print(avg)
print(np.mean(data[:,:1]))

18.4
18.4


Extract math_marks of all students

In [9]:
marks = data[:,1]
print(marks)

[85 92 76 65 90]


Find the highest science_marks

In [10]:
marks = data[:,2]
print(np.max(marks, axis=0))

95


Get details of the students who scored more than 90 in math

In [11]:
print(data[data[:,1] > 90])


[[19 92 88]]


Increase math marks of all students by 5

In [12]:
data[:,1] += 5
print(data)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]


Find how many students are younger than 19

In [13]:
len(data[data[:,0] < 19])

3

Calculate the average marks in each subject (column-wise mean)

In [14]:
print(np.mean(data[:,1:], axis=0))

[86.6 83.2]


Get data of students who scored at least 80 in both subjects

In [15]:
print(data[(data[:,1] >= 80) & (data[:,2] >= 80)])

[[19 97 88]
 [17 81 95]
 [20 95 85]]


Replace all science marks < 75 with 0

In [16]:
data[:,2][data[:,2] < 75] = 0
print(data)


[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70  0]
 [20 95 85]]
